Feature/eq2 222
MathieuDonofrio/InternshipManager pull request #36
Opened 2020-11-28 01:56 UTC by hichemfredj

2020-11-28 02:25 UTC, progdev8201 commented on src/main/resources/internship-manager/src/components/ManageAccess.js
> +    // position: 'relative',
ici ta laisser des commentaires

2020-11-28 02:27 UTC, progdev8201 requested changes
enleve ton commentaire

2020-11-28 20:18 UTC, progdev8201 approved these changes

2020-11-30 05:20 UTC, MathieuDonofrio approved these changes

2020-11-30 05:20 UTC, merged