Feature/eq2 132
MathieuDonofrio/InternshipManager pull request #9
Opened 2020-10-17 04:14 UTC by progdev8201

2020-10-17 17:33 UTC, 158stev commented on src/main/java/cal/internshipmanager/repository/InternshipApplicationRepository.java
> +    List<InternshipApplication> findAllByOfferUniqueId(UUID offerUniqueId);
Probably add a space?

2020-10-17 17:34 UTC, progdev8201 commented on src/main/java/cal/internshipmanager/repository/InternshipApplicationRepository.java
> +    List<InternshipApplication> findAllByOfferUniqueId(UUID offerUniqueId);
will do

2020-10-19 22:45 UTC, MathieuDonofrio requested changes

2020-10-19 22:45 UTC, MathieuDonofrio commented on src/main/java/cal/internshipmanager/service/InternshipOfferService.java
> +    public InternshipOfferListResponse findAllByEmployer(@NotNull UUID uniqueId){
Use @ExistingUser

2020-10-19 22:45 UTC, MathieuDonofrio commented on src/main/java/cal/internshipmanager/service/InternshipApplicationService.java
> +    public InternshipApplicationListResponse findByOffer(@Valid UUID offerUniqueId) {
Use @ExistingInternshipOffer

2020-10-19 22:45 UTC, MathieuDonofrio commented on src/test/java/cal/internshipmanager/service/InternshipApplicationServiceTest.java
> +        Mockito.when(internshipApplicationRepository.findAllByOfferUniqueId(Mockito.any())).thenReturn(List.of(internshipApplication));
Ici il est possible d'utiliser internshipApplication.getUniqueId() en place de Mockito.any() pour rendre scope du test plus precis

2020-10-19 22:45 UTC, MathieuDonofrio commented on src/test/java/cal/internshipmanager/service/InternshipOfferServiceTest.java
> +        Mockito.when(internshipOfferRepository.findAllByEmployer(Mockito.any())).thenReturn(List.of(internshipOffer));
Ici aussi tu peut utiliser internshipOffer.getEmployer() en place de Mockito.any()

2020-10-20 23:55 UTC, MathieuDonofrio approved these changes

2020-10-20 23:59 UTC, merged